/* vim: set fileencoding=utf-8:
 * 
 *                   GNU GENERAL PUBLIC LICENSE
 *                       Version 2, June 1991
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * @author  buaabyl@gmail.com
 * @ref sunpinyin
 *
 *  2012.10.01
 *      I read sunpinyin source code, and design this library,
 *      so the license must be GPL or LGPL
 *      implement it in flex+bison
 *
 *  2017.04.16
 *      rewrite by hand, remove flex and bison
 *      optimize
 *
 *  2017.08.01
 *      optimize
 */
/***************************************************/
/*       !!! DO NOT MODIFY THIS FILE !!!           */ 
/*    generated by lime_pinyin.py automatically    */
/*                                                 */
/***************************************************/

#ifndef LIME_PINYIN_H_D34BCEBF_B4AD_84DB_4495_CC6CB12C84C3_INCLUDED_
#define LIME_PINYIN_H_D34BCEBF_B4AD_84DB_4495_CC6CB12C84C3_INCLUDED_

#define MAX_PRONOUNCE_LENGTH   4
#define MAX_PRONOUNCE_INDEX    56
#define MAX_CONSONANT_INDEX    23 // zh

/*
 * @brief   convert string to internal defined value
 * @return  [0, MAX_PRONOUNCE_INDEX)
 * @retval  -1      invalid
 */
int lime_map_by_pronounce(const char* s, int len);

const char* lime_map_to_pronounce(int id);

int lime_is_paired_by_id(int consonant, int vowel);
int lime_is_paired_by_str(const char* consonant, const char* vowel);

#endif

