/* vim: set fileencoding=utf-8:
 * 
 *                   GNU GENERAL PUBLIC LICENSE
 *                       Version 2, June 1991
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; see the file COPYING.  If not, write to
 * the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * @author  buaabyl@gmail.com
 * @ref sunpinyin
 *
 *  2012.10.01
 *      I read sunpinyin source code, and design this library,
 *      so the license must be GPL or LGPL
 *      implement it in flex+bison
 *
 */
/***************************************************/
/*       !!! DO NOT MODIFY THIS FILE !!!           */ 
/*    generated by lime_pinyin.py automatically    */
/*                                                 */
/***************************************************/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "lime_pinyin.h"

/*
 * @brief   valid consonant and vowel pair lookup table
 * @descriptions
 *      array[consonant_id][vowel_id - MAX_CONSONANT_INDEX - 1]
 */
static const int _pair_array[24][34] = {
    { // 0: " "
        1/*a     */,   1/*ai    */,   1/*an    */,   1/*ang   */,   1/*ao    */,   1/*e     */,   1/*ei    */,   1/*en    */,   
        1/*eng   */,   1/*er    */,   0/*i     */,   0/*ia    */,   0/*ian   */,   0/*iang  */,   0/*iao   */,   0/*ie    */,   
        0/*in    */,   0/*ing   */,   0/*iong  */,   0/*iu    */,   1/*o     */,   0/*ong   */,   1/*ou    */,   0/*u     */,   
        0/*ua    */,   0/*uai   */,   0/*uan   */,   0/*uang  */,   0/*ue    */,   0/*ui    */,   0/*un    */,   0/*uo    */,   
        0/*v     */,   
    },
    { // 1: "b"
        1/*ba    */,   1/*bai   */,   1/*ban   */,   1/*bang  */,   1/*bao   */,   0/*be    */,   1/*bei   */,   1/*ben   */,   
        1/*beng  */,   0/*ber   */,   1/*bi    */,   0/*bia   */,   1/*bian  */,   0/*biang */,   1/*biao  */,   1/*bie   */,   
        1/*bin   */,   1/*bing  */,   0/*biong */,   0/*biu   */,   1/*bo    */,   0/*bong  */,   0/*bou   */,   1/*bu    */,   
        0/*bua   */,   0/*buai  */,   0/*buan  */,   0/*buang */,   0/*bue   */,   0/*bui   */,   0/*bun   */,   0/*buo   */,   
        0/*bv    */,   
    },
    { // 2: "c"
        1/*ca    */,   1/*cai   */,   1/*can   */,   1/*cang  */,   1/*cao   */,   1/*ce    */,   1/*cei   */,   1/*cen   */,   
        1/*ceng  */,   0/*cer   */,   1/*ci    */,   0/*cia   */,   0/*cian  */,   0/*ciang */,   0/*ciao  */,   0/*cie   */,   
        0/*cin   */,   0/*cing  */,   0/*ciong */,   0/*ciu   */,   0/*co    */,   1/*cong  */,   1/*cou   */,   1/*cu    */,   
        0/*cua   */,   0/*cuai  */,   1/*cuan  */,   0/*cuang */,   0/*cue   */,   1/*cui   */,   1/*cun   */,   1/*cuo   */,   
        0/*cv    */,   
    },
    { // 3: "ch"
        1/*cha   */,   1/*chai  */,   1/*chan  */,   1/*chang */,   1/*chao  */,   1/*che   */,   0/*chei  */,   1/*chen  */,   
        1/*cheng */,   0/*cher  */,   1/*chi   */,   0/*chia  */,   0/*chian */,   0/*chiang*/,   0/*chiao */,   0/*chie  */,   
        0/*chin  */,   0/*ching */,   0/*chiong*/,   0/*chiu  */,   0/*cho   */,   1/*chong */,   1/*chou  */,   1/*chu   */,   
        1/*chua  */,   1/*chuai */,   1/*chuan */,   1/*chuang*/,   0/*chue  */,   1/*chui  */,   1/*chun  */,   1/*chuo  */,   
        0/*chv   */,   
    },
    { // 4: "d"
        1/*da    */,   1/*dai   */,   1/*dan   */,   1/*dang  */,   1/*dao   */,   1/*de    */,   1/*dei   */,   1/*den   */,   
        1/*deng  */,   0/*der   */,   1/*di    */,   1/*dia   */,   1/*dian  */,   0/*diang */,   1/*diao  */,   1/*die   */,   
        0/*din   */,   1/*ding  */,   0/*diong */,   1/*diu   */,   0/*do    */,   1/*dong  */,   1/*dou   */,   1/*du    */,   
        0/*dua   */,   0/*duai  */,   1/*duan  */,   0/*duang */,   0/*due   */,   1/*dui   */,   1/*dun   */,   1/*duo   */,   
        0/*dv    */,   
    },
    { // 5: "f"
        1/*fa    */,   0/*fai   */,   1/*fan   */,   1/*fang  */,   0/*fao   */,   0/*fe    */,   1/*fei   */,   1/*fen   */,   
        1/*feng  */,   0/*fer   */,   0/*fi    */,   0/*fia   */,   0/*fian  */,   0/*fiang */,   1/*fiao  */,   0/*fie   */,   
        0/*fin   */,   0/*fing  */,   0/*fiong */,   0/*fiu   */,   1/*fo    */,   0/*fong  */,   1/*fou   */,   1/*fu    */,   
        0/*fua   */,   0/*fuai  */,   0/*fuan  */,   0/*fuang */,   0/*fue   */,   0/*fui   */,   0/*fun   */,   0/*fuo   */,   
        0/*fv    */,   
    },
    { // 6: "g"
        1/*ga    */,   1/*gai   */,   1/*gan   */,   1/*gang  */,   1/*gao   */,   1/*ge    */,   1/*gei   */,   1/*gen   */,   
        1/*geng  */,   0/*ger   */,   0/*gi    */,   0/*gia   */,   0/*gian  */,   0/*giang */,   0/*giao  */,   0/*gie   */,   
        0/*gin   */,   0/*ging  */,   0/*giong */,   0/*giu   */,   0/*go    */,   1/*gong  */,   1/*gou   */,   1/*gu    */,   
        1/*gua   */,   1/*guai  */,   1/*guan  */,   1/*guang */,   0/*gue   */,   1/*gui   */,   1/*gun   */,   1/*guo   */,   
        0/*gv    */,   
    },
    { // 7: "h"
        1/*ha    */,   1/*hai   */,   1/*han   */,   1/*hang  */,   1/*hao   */,   1/*he    */,   1/*hei   */,   1/*hen   */,   
        1/*heng  */,   0/*her   */,   0/*hi    */,   0/*hia   */,   0/*hian  */,   0/*hiang */,   0/*hiao  */,   0/*hie   */,   
        0/*hin   */,   0/*hing  */,   0/*hiong */,   0/*hiu   */,   0/*ho    */,   1/*hong  */,   1/*hou   */,   1/*hu    */,   
        1/*hua   */,   1/*huai  */,   1/*huan  */,   1/*huang */,   0/*hue   */,   1/*hui   */,   1/*hun   */,   1/*huo   */,   
        0/*hv    */,   
    },
    { // 8: "j"
        0/*ja    */,   0/*jai   */,   0/*jan   */,   0/*jang  */,   0/*jao   */,   0/*je    */,   0/*jei   */,   0/*jen   */,   
        0/*jeng  */,   0/*jer   */,   1/*ji    */,   1/*jia   */,   1/*jian  */,   1/*jiang */,   1/*jiao  */,   1/*jie   */,   
        1/*jin   */,   1/*jing  */,   1/*jiong */,   1/*jiu   */,   0/*jo    */,   0/*jong  */,   0/*jou   */,   1/*ju    */,   
        0/*jua   */,   0/*juai  */,   1/*juan  */,   0/*juang */,   1/*jue   */,   0/*jui   */,   1/*jun   */,   0/*juo   */,   
        0/*jv    */,   
    },
    { // 9: "k"
        1/*ka    */,   1/*kai   */,   1/*kan   */,   1/*kang  */,   1/*kao   */,   1/*ke    */,   1/*kei   */,   1/*ken   */,   
        1/*keng  */,   0/*ker   */,   0/*ki    */,   0/*kia   */,   0/*kian  */,   0/*kiang */,   0/*kiao  */,   0/*kie   */,   
        0/*kin   */,   0/*king  */,   0/*kiong */,   0/*kiu   */,   0/*ko    */,   1/*kong  */,   1/*kou   */,   1/*ku    */,   
        1/*kua   */,   1/*kuai  */,   1/*kuan  */,   1/*kuang */,   0/*kue   */,   1/*kui   */,   1/*kun   */,   1/*kuo   */,   
        0/*kv    */,   
    },
    { // 10: "l"
        1/*la    */,   1/*lai   */,   1/*lan   */,   1/*lang  */,   1/*lao   */,   1/*le    */,   1/*lei   */,   0/*len   */,   
        1/*leng  */,   0/*ler   */,   1/*li    */,   1/*lia   */,   1/*lian  */,   1/*liang */,   1/*liao  */,   1/*lie   */,   
        1/*lin   */,   1/*ling  */,   0/*liong */,   1/*liu   */,   1/*lo    */,   1/*long  */,   1/*lou   */,   1/*lu    */,   
        0/*lua   */,   0/*luai  */,   1/*luan  */,   0/*luang */,   1/*lue   */,   0/*lui   */,   1/*lun   */,   1/*luo   */,   
        1/*lv    */,   
    },
    { // 11: "m"
        1/*ma    */,   1/*mai   */,   1/*man   */,   1/*mang  */,   1/*mao   */,   1/*me    */,   1/*mei   */,   1/*men   */,   
        1/*meng  */,   0/*mer   */,   1/*mi    */,   0/*mia   */,   1/*mian  */,   0/*miang */,   1/*miao  */,   1/*mie   */,   
        1/*min   */,   1/*ming  */,   0/*miong */,   1/*miu   */,   1/*mo    */,   0/*mong  */,   1/*mou   */,   1/*mu    */,   
        0/*mua   */,   0/*muai  */,   0/*muan  */,   0/*muang */,   0/*mue   */,   0/*mui   */,   0/*mun   */,   0/*muo   */,   
        0/*mv    */,   
    },
    { // 12: "n"
        1/*na    */,   1/*nai   */,   1/*nan   */,   1/*nang  */,   1/*nao   */,   1/*ne    */,   1/*nei   */,   1/*nen   */,   
        1/*neng  */,   0/*ner   */,   1/*ni    */,   0/*nia   */,   1/*nian  */,   1/*niang */,   1/*niao  */,   1/*nie   */,   
        1/*nin   */,   1/*ning  */,   0/*niong */,   1/*niu   */,   0/*no    */,   1/*nong  */,   1/*nou   */,   1/*nu    */,   
        0/*nua   */,   0/*nuai  */,   1/*nuan  */,   0/*nuang */,   1/*nue   */,   0/*nui   */,   1/*nun   */,   1/*nuo   */,   
        1/*nv    */,   
    },
    { // 13: "p"
        1/*pa    */,   1/*pai   */,   1/*pan   */,   1/*pang  */,   1/*pao   */,   0/*pe    */,   1/*pei   */,   1/*pen   */,   
        1/*peng  */,   0/*per   */,   1/*pi    */,   0/*pia   */,   1/*pian  */,   0/*piang */,   1/*piao  */,   1/*pie   */,   
        1/*pin   */,   1/*ping  */,   0/*piong */,   0/*piu   */,   1/*po    */,   0/*pong  */,   1/*pou   */,   1/*pu    */,   
        0/*pua   */,   0/*puai  */,   0/*puan  */,   0/*puang */,   0/*pue   */,   0/*pui   */,   0/*pun   */,   0/*puo   */,   
        0/*pv    */,   
    },
    { // 14: "q"
        0/*qa    */,   0/*qai   */,   0/*qan   */,   0/*qang  */,   0/*qao   */,   0/*qe    */,   0/*qei   */,   0/*qen   */,   
        0/*qeng  */,   0/*qer   */,   1/*qi    */,   1/*qia   */,   1/*qian  */,   1/*qiang */,   1/*qiao  */,   1/*qie   */,   
        1/*qin   */,   1/*qing  */,   1/*qiong */,   1/*qiu   */,   0/*qo    */,   0/*qong  */,   0/*qou   */,   1/*qu    */,   
        0/*qua   */,   0/*quai  */,   1/*quan  */,   0/*quang */,   1/*que   */,   0/*qui   */,   1/*qun   */,   0/*quo   */,   
        0/*qv    */,   
    },
    { // 15: "r"
        0/*ra    */,   0/*rai   */,   1/*ran   */,   1/*rang  */,   1/*rao   */,   1/*re    */,   0/*rei   */,   1/*ren   */,   
        1/*reng  */,   0/*rer   */,   1/*ri    */,   0/*ria   */,   0/*rian  */,   0/*riang */,   0/*riao  */,   0/*rie   */,   
        0/*rin   */,   0/*ring  */,   0/*riong */,   0/*riu   */,   0/*ro    */,   1/*rong  */,   1/*rou   */,   1/*ru    */,   
        1/*rua   */,   0/*ruai  */,   1/*ruan  */,   0/*ruang */,   0/*rue   */,   1/*rui   */,   1/*run   */,   1/*ruo   */,   
        0/*rv    */,   
    },
    { // 16: "s"
        1/*sa    */,   1/*sai   */,   1/*san   */,   1/*sang  */,   1/*sao   */,   1/*se    */,   0/*sei   */,   1/*sen   */,   
        1/*seng  */,   0/*ser   */,   1/*si    */,   0/*sia   */,   0/*sian  */,   0/*siang */,   0/*siao  */,   0/*sie   */,   
        0/*sin   */,   0/*sing  */,   0/*siong */,   0/*siu   */,   0/*so    */,   1/*song  */,   1/*sou   */,   1/*su    */,   
        0/*sua   */,   0/*suai  */,   1/*suan  */,   0/*suang */,   0/*sue   */,   1/*sui   */,   1/*sun   */,   1/*suo   */,   
        0/*sv    */,   
    },
    { // 17: "sh"
        1/*sha   */,   1/*shai  */,   1/*shan  */,   1/*shang */,   1/*shao  */,   1/*she   */,   1/*shei  */,   1/*shen  */,   
        1/*sheng */,   0/*sher  */,   1/*shi   */,   0/*shia  */,   0/*shian */,   0/*shiang*/,   0/*shiao */,   0/*shie  */,   
        0/*shin  */,   0/*shing */,   0/*shiong*/,   0/*shiu  */,   0/*sho   */,   0/*shong */,   1/*shou  */,   1/*shu   */,   
        1/*shua  */,   1/*shuai */,   1/*shuan */,   1/*shuang*/,   0/*shue  */,   1/*shui  */,   1/*shun  */,   1/*shuo  */,   
        0/*shv   */,   
    },
    { // 18: "t"
        1/*ta    */,   1/*tai   */,   1/*tan   */,   1/*tang  */,   1/*tao   */,   1/*te    */,   1/*tei   */,   0/*ten   */,   
        1/*teng  */,   0/*ter   */,   1/*ti    */,   0/*tia   */,   1/*tian  */,   0/*tiang */,   1/*tiao  */,   1/*tie   */,   
        0/*tin   */,   1/*ting  */,   0/*tiong */,   0/*tiu   */,   0/*to    */,   1/*tong  */,   1/*tou   */,   1/*tu    */,   
        0/*tua   */,   0/*tuai  */,   1/*tuan  */,   0/*tuang */,   0/*tue   */,   1/*tui   */,   1/*tun   */,   1/*tuo   */,   
        0/*tv    */,   
    },
    { // 19: "w"
        1/*wa    */,   1/*wai   */,   1/*wan   */,   1/*wang  */,   0/*wao   */,   0/*we    */,   1/*wei   */,   1/*wen   */,   
        1/*weng  */,   0/*wer   */,   0/*wi    */,   0/*wia   */,   0/*wian  */,   0/*wiang */,   0/*wiao  */,   0/*wie   */,   
        0/*win   */,   0/*wing  */,   0/*wiong */,   0/*wiu   */,   1/*wo    */,   0/*wong  */,   0/*wou   */,   1/*wu    */,   
        0/*wua   */,   0/*wuai  */,   0/*wuan  */,   0/*wuang */,   0/*wue   */,   0/*wui   */,   0/*wun   */,   0/*wuo   */,   
        0/*wv    */,   
    },
    { // 20: "x"
        0/*xa    */,   0/*xai   */,   0/*xan   */,   0/*xang  */,   0/*xao   */,   0/*xe    */,   0/*xei   */,   0/*xen   */,   
        0/*xeng  */,   0/*xer   */,   1/*xi    */,   1/*xia   */,   1/*xian  */,   1/*xiang */,   1/*xiao  */,   1/*xie   */,   
        1/*xin   */,   1/*xing  */,   1/*xiong */,   1/*xiu   */,   0/*xo    */,   0/*xong  */,   0/*xou   */,   1/*xu    */,   
        0/*xua   */,   0/*xuai  */,   1/*xuan  */,   0/*xuang */,   1/*xue   */,   0/*xui   */,   1/*xun   */,   0/*xuo   */,   
        0/*xv    */,   
    },
    { // 21: "y"
        1/*ya    */,   0/*yai   */,   1/*yan   */,   1/*yang  */,   1/*yao   */,   1/*ye    */,   0/*yei   */,   0/*yen   */,   
        0/*yeng  */,   0/*yer   */,   1/*yi    */,   0/*yia   */,   0/*yian  */,   0/*yiang */,   0/*yiao  */,   0/*yie   */,   
        1/*yin   */,   1/*ying  */,   0/*yiong */,   0/*yiu   */,   1/*yo    */,   1/*yong  */,   1/*you   */,   1/*yu    */,   
        0/*yua   */,   0/*yuai  */,   1/*yuan  */,   0/*yuang */,   1/*yue   */,   0/*yui   */,   1/*yun   */,   0/*yuo   */,   
        0/*yv    */,   
    },
    { // 22: "z"
        1/*za    */,   1/*zai   */,   1/*zan   */,   1/*zang  */,   1/*zao   */,   1/*ze    */,   1/*zei   */,   1/*zen   */,   
        1/*zeng  */,   0/*zer   */,   1/*zi    */,   0/*zia   */,   0/*zian  */,   0/*ziang */,   0/*ziao  */,   0/*zie   */,   
        0/*zin   */,   0/*zing  */,   0/*ziong */,   0/*ziu   */,   0/*zo    */,   1/*zong  */,   1/*zou   */,   1/*zu    */,   
        0/*zua   */,   0/*zuai  */,   1/*zuan  */,   0/*zuang */,   0/*zue   */,   1/*zui   */,   1/*zun   */,   1/*zuo   */,   
        0/*zv    */,   
    },
    { // 23: "zh"
        1/*zha   */,   1/*zhai  */,   1/*zhan  */,   1/*zhang */,   1/*zhao  */,   1/*zhe   */,   1/*zhei  */,   1/*zhen  */,   
        1/*zheng */,   0/*zher  */,   1/*zhi   */,   0/*zhia  */,   0/*zhian */,   0/*zhiang*/,   0/*zhiao */,   0/*zhie  */,   
        0/*zhin  */,   0/*zhing */,   0/*zhiong*/,   0/*zhiu  */,   0/*zho   */,   1/*zhong */,   1/*zhou  */,   1/*zhu   */,   
        1/*zhua  */,   1/*zhuai */,   1/*zhuan */,   1/*zhuang*/,   0/*zhue  */,   1/*zhui  */,   1/*zhun  */,   1/*zhuo  */,   
        0/*zhv   */,   
    },
};


int lime_map_by_pronounce(const char* s, int len)
{
    if (len == -1) {
        len = strlen(s);
    }
    if (strncmp(s, " "   , len) == 0) return 0;
    if (strncmp(s, "b"   , len) == 0) return 1;
    if (strncmp(s, "c"   , len) == 0) return 2;
    if (strncmp(s, "ch"  , len) == 0) return 3;
    if (strncmp(s, "d"   , len) == 0) return 4;
    if (strncmp(s, "f"   , len) == 0) return 5;
    if (strncmp(s, "g"   , len) == 0) return 6;
    if (strncmp(s, "h"   , len) == 0) return 7;
    if (strncmp(s, "j"   , len) == 0) return 8;
    if (strncmp(s, "k"   , len) == 0) return 9;
    if (strncmp(s, "l"   , len) == 0) return 10;
    if (strncmp(s, "m"   , len) == 0) return 11;
    if (strncmp(s, "n"   , len) == 0) return 12;
    if (strncmp(s, "p"   , len) == 0) return 13;
    if (strncmp(s, "q"   , len) == 0) return 14;
    if (strncmp(s, "r"   , len) == 0) return 15;
    if (strncmp(s, "s"   , len) == 0) return 16;
    if (strncmp(s, "sh"  , len) == 0) return 17;
    if (strncmp(s, "t"   , len) == 0) return 18;
    if (strncmp(s, "w"   , len) == 0) return 19;
    if (strncmp(s, "x"   , len) == 0) return 20;
    if (strncmp(s, "y"   , len) == 0) return 21;
    if (strncmp(s, "z"   , len) == 0) return 22;
    if (strncmp(s, "zh"  , len) == 0) return 23;
    if (strncmp(s, "a"   , len) == 0) return 24;
    if (strncmp(s, "ai"  , len) == 0) return 25;
    if (strncmp(s, "an"  , len) == 0) return 26;
    if (strncmp(s, "ang" , len) == 0) return 27;
    if (strncmp(s, "ao"  , len) == 0) return 28;
    if (strncmp(s, "e"   , len) == 0) return 29;
    if (strncmp(s, "ei"  , len) == 0) return 30;
    if (strncmp(s, "en"  , len) == 0) return 31;
    if (strncmp(s, "eng" , len) == 0) return 32;
    if (strncmp(s, "er"  , len) == 0) return 33;
    if (strncmp(s, "i"   , len) == 0) return 34;
    if (strncmp(s, "ia"  , len) == 0) return 35;
    if (strncmp(s, "ian" , len) == 0) return 36;
    if (strncmp(s, "iang", len) == 0) return 37;
    if (strncmp(s, "iao" , len) == 0) return 38;
    if (strncmp(s, "ie"  , len) == 0) return 39;
    if (strncmp(s, "in"  , len) == 0) return 40;
    if (strncmp(s, "ing" , len) == 0) return 41;
    if (strncmp(s, "iong", len) == 0) return 42;
    if (strncmp(s, "iu"  , len) == 0) return 43;
    if (strncmp(s, "o"   , len) == 0) return 44;
    if (strncmp(s, "ong" , len) == 0) return 45;
    if (strncmp(s, "ou"  , len) == 0) return 46;
    if (strncmp(s, "u"   , len) == 0) return 47;
    if (strncmp(s, "ua"  , len) == 0) return 48;
    if (strncmp(s, "uai" , len) == 0) return 49;
    if (strncmp(s, "uan" , len) == 0) return 50;
    if (strncmp(s, "uang", len) == 0) return 51;
    if (strncmp(s, "ue"  , len) == 0) return 52;
    if (strncmp(s, "ui"  , len) == 0) return 53;
    if (strncmp(s, "un"  , len) == 0) return 54;
    if (strncmp(s, "uo"  , len) == 0) return 55;
    if (strncmp(s, "v"   , len) == 0) return 56;
    return -1;
}

const char* lime_map_to_pronounce(int id)
{
    if (id ==  0) return " ";
    if (id ==  1) return "b";
    if (id ==  2) return "c";
    if (id ==  3) return "ch";
    if (id ==  4) return "d";
    if (id ==  5) return "f";
    if (id ==  6) return "g";
    if (id ==  7) return "h";
    if (id ==  8) return "j";
    if (id ==  9) return "k";
    if (id == 10) return "l";
    if (id == 11) return "m";
    if (id == 12) return "n";
    if (id == 13) return "p";
    if (id == 14) return "q";
    if (id == 15) return "r";
    if (id == 16) return "s";
    if (id == 17) return "sh";
    if (id == 18) return "t";
    if (id == 19) return "w";
    if (id == 20) return "x";
    if (id == 21) return "y";
    if (id == 22) return "z";
    if (id == 23) return "zh";
    if (id == 24) return "a";
    if (id == 25) return "ai";
    if (id == 26) return "an";
    if (id == 27) return "ang";
    if (id == 28) return "ao";
    if (id == 29) return "e";
    if (id == 30) return "ei";
    if (id == 31) return "en";
    if (id == 32) return "eng";
    if (id == 33) return "er";
    if (id == 34) return "i";
    if (id == 35) return "ia";
    if (id == 36) return "ian";
    if (id == 37) return "iang";
    if (id == 38) return "iao";
    if (id == 39) return "ie";
    if (id == 40) return "in";
    if (id == 41) return "ing";
    if (id == 42) return "iong";
    if (id == 43) return "iu";
    if (id == 44) return "o";
    if (id == 45) return "ong";
    if (id == 46) return "ou";
    if (id == 47) return "u";
    if (id == 48) return "ua";
    if (id == 49) return "uai";
    if (id == 50) return "uan";
    if (id == 51) return "uang";
    if (id == 52) return "ue";
    if (id == 53) return "ui";
    if (id == 54) return "un";
    if (id == 55) return "uo";
    if (id == 56) return "v";
    return NULL;
}


int lime_is_paired_by_id(int consonant, int vowel)
{
    if (consonant > MAX_CONSONANT_INDEX) {
        return 0;
    }
    if (vowel <= MAX_CONSONANT_INDEX) {
        return 0;
    }
    if (vowel > MAX_PRONOUNCE_INDEX) {
        return 0;
    }

    if (_pair_array[consonant][vowel - MAX_CONSONANT_INDEX - 1]) {
        return 1;
    }

    return 0;
}

int lime_is_paired_by_str(const char* consonant, const char* vowel)
{
    int consonant_id;
    int vowel_id;

    consonant_id = lime_map_by_pronounce(consonant, -1);
    vowel_id     = lime_map_by_pronounce(vowel, -1);

    return lime_is_paired_by_id(consonant_id, vowel_id);
}

